### ISSUE TITLE
ac_query not working on v0.9.9

### ISSUE THREAD

**Issue by jamesmyatt** [ssato/python-anyconfig#108]
I have anyconfig v0.9.9 installed via conda-forge and the example of using ac_query from the README.md is not working. I get the following:

```
>>> dic = dict(a=dict(b=[dict(c="C", d=0)]))
>>> anyconfig.loads(anyconfig.dumps(dic, ac_parser="json"), ac_parser="json", ac_query="a.b[0].c")
{'a': {'b': [{'c': 'C', 'd': 0}]}}
```

**Comment by jamesmyatt** [comment]
Ah. The problem is that jmespath was not installed. I think it would be better for `ac_query` to raise a ValueError if jmespath is not installed?

**Comment by ssato** [comment]
Sorry to late and thanks a lot for your suggestion! I'll look the code closely to consider that change this week.

**Comment by ssato** [comment]
I think that b902fe5 may resolve this.
