### ISSUE TITLE
In Centos7.7 has error when install anyconfig

### ISSUE THREAD

**Issue by Wangweilai1** [ssato/python-anyconfig#114]
I found a bug, in Centos7.7 and python2 or python3  pip install anyconfig is ok, but import anyconfig has error ModuleNotFoundError: No module named 'anyconfig' ,  so I pip install anycofig==0.9.7 , version 9.0.7 is ok when import anyconfig. version 0.9.8, 0.9.9 and 0.9.10 can't use in cenots7.7.

**Comment by Wangweilai1** [comment]
![image](https://user-images.githubusercontent.com/15275988/74927042-e1effc80-5411-11ea-9919-78317dc5016e.png)
![image](https://user-images.githubusercontent.com/15275988/74927087-f633f980-5411-11ea-8c09-5a7d9996606e.png)

**Comment by ssato** [comment]
Thanks a lot your report!

One thing I want to check is the version of setuptools you're using.
Could you please show me the output of "rpm -qa python\*setuptools" ?

**Comment by Wangweilai1** [comment]
![image](https://user-images.githubusercontent.com/15275988/75082834-8415fe80-5550-11ea-9129-f07ef12ddf1c.png)

**Comment by ssato** [comment]
Sorry to very late but I've just released 0.9.11 may resolve this, I guess. Also, I've upload the wheel package and the problem becomes disappeared if CentOS 7.x can use it.

I close this but please re-open this issue if you have any further problems on this.
