### ISSUE TITLE
make package PEP-561 compatible (add py.typed)

### ISSUE THREAD

**Issue by SimonDR-Boltzmann** [ssato/python-anyconfig#141]
**Is your feature request related to a problem? Please describe.**
When importing this package and using mypy (without the `--follow-imports=skip` option), mypy generates an error:
"error: Skipping analyzing "anyconfig": found module but no type hints or library stubs"

**Describe the solution you'd like**
The type hints in this package seem quite complete, I think all that is needed is to add a py.typed file.
see https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages for the how-to.

**Comment by ssato** [comment]
Thanks a lot! I'll work on this.

**Comment by ssato** [comment]
Excuse me for late updates.

I pushed a commit 10c4346 may resolve this, I guess. If it looks OK, I'll release the new version contains that.

**Comment by ssato** [comment]
Thanks for your check and quick response! OK, I'll release it ASAP.
