### ISSUE TITLE
Do not use assert in main application code

### ISSUE THREAD

**Issue by Grokzen** [ssato/python-anyconfig#15]
Hi.

While looking through merge strategies i found that you are using asserts in the main application code https://github.com/ssato/python-anyconfig/blob/master/anyconfig/api.py#L131

It would look wierd if i ran the code and i got a assertion error when not running the tests. It should either return with some error code or raise a custom exception.

**Comment by ssato** [comment]
Absolutely right. I forgot to remove these assertions. Thanks a lot for your report and suggestions!

I guess the last commit #2cea91a9ad may be an answer for this issue.
So, could you please take a loot at it?

**Comment by Grokzen** [comment]
The commit looks greak :]
