### ISSUE TITLE
Update toml parser

### ISSUE THREAD

**Issue by flying-sheep** [ssato/python-anyconfig#153]
**Is your feature request related to a problem? Please describe.**
The “toml“ project on PyPI is old and unmaintained.

**Describe the solution you'd like**
Use the stdlib’s `tomllib` on Python 3.11 and `tomli` on lower Python versions

**Describe alternatives you've considered**
Get uiri to pick up development on toml? Probably no alternatives.

**Comment by ssato** [comment]
Thanks a lot for letting me know these libs I was not aware of.

I added support of {tomllib, tomli-w}, {tomli, tomli-w} and tomlkit in 4a000c5 .

**Comment by flying-sheep** [comment]
Great! That for sure fixes the problem with the `toml` package being essentially unmaintained.

One thing that would be great was if TOML reading capabilities worked on Python 3.11 without `tomli-w` being installed. Some packages just read config files using `anyconfig` and don’t write them. Currently, `anyconfig` assumes that every “Parser” is also a serializer.

Independently, this

https://github.com/ssato/python-anyconfig/blob/4a000c57be426e4f3b46654c087a5309871329d1/setup.cfg#L70-L71

should probably be changed to this

```ini
toml =
    tomli; python_version < "3.11"
    tomli-w
```

**Comment by ssato** [comment]
Thanks a lot. I applied the fix also.

**Comment by flying-sheep** [comment]
Great! Will there be a release soonish so it can be used?

**Comment by ssato** [comment]
Sorry to late reply. I'm now preparing the next release will contain this change and updates.

**Comment by ssato** [comment]
FYI. I released 0.14.0 contains the fix for this.

**Comment by flying-sheep** [comment]
thank you for the info, it’s appreciated!
