### ISSUE TITLE
[BUG] Anyconfig load the wrong file -  with Jinja2 templating.

### ISSUE THREAD

**Issue by quamilek** [ssato/python-anyconfig#18]
This is a tree of files where error occured:
```
└── current_dir
    ├── test
    │   └── location
    │       └── config.yaml
    └── config.yaml
```

When i run:

```python
context = {'name': 'James Bond'}
path = 'test/location/config.yaml'
config = anyconfig.load(
    path, 'yaml', ac_template=True, ac_context=context,
)
```

Anyconfig load file `config.yaml` instead of  `test/location/config.yaml`, this is unexpected action.
Expected behavior is, when Anyconfig load `test/location/config.yaml` file.

Errors occured in:
https://github.com/ssato/python-anyconfig/blob/master/anyconfig/template.py#L84
Now it is:

```
return env.get_template(os.path.basename(template_file)).render(**ctx)
```

I think should be:

```
return env.get_template(template_file).render(**ctx)
```

Full example of  code to explanation this bug:
https://gist.github.com/quamilek/95487915f66c4edc7441

**Comment by ssato** [comment]
Thanks a lot for your report!

I've just checked in a part of possible fixes in anyconfig.template side. 
It seems that your test case still fails so I'll investigate it further.

**Comment by ssato** [comment]
I added one more test case in the commit, e2ae25d401. 
Could you please take a loot at it?

**Comment by quamilek** [comment]
Now work correctly. Thanks for your quick response.
When would you like release a new version?

**Comment by ssato** [comment]
OK, I'll close this issue. Thanks a lot for the confirmation!

About the next release, I'm planning to release it this weekend hopefully w/ fixes/refactorings and some minor enhancements.

**Comment by kamilchm** [comment]
What with the release of this fix? We're using monkey pathed 0.0.7 because of it and it would be great to just upgrade anyconfig from pypi :)

**Comment by ssato** [comment]
Sorry to late. I've been busy w/ my day job and it also took some more to finish the rest of work
for the 0.0.8 release than I thought.

Anyway, I've just uploaded the 0.0.8 release. Could you please try it?

**Comment by kamilchm** [comment]
It works. Thx for your quick response!

**Comment by ssato** [comment]
I've closed this now. If you have any related issues, could you re-open another issue, please?
