### ISSUE TITLE
anyconfig.mergeabledict.MergeableDict is too complex and ugly

### ISSUE THREAD

**Issue by ssato** [ssato/python-anyconfig#37]
The class MergeableDict is too complex and has ugly update_* methods.
Also it's not compat with dict.update.

**Comment by ssato** [comment]
I've been continued working hardly to fix this issue in the mdict branch.

**Comment by AbsoluteMSTR** [comment]
possibly do a recursive wrap around [collections.ChainMap](https://docs.python.org/3/library/collections.html#collections.ChainMap), will need to be backported to support python 2.7 which I submitted to [pies](https://github.com/timothycrosley/pies/blob/develop/pies/collections.py). Could use that as cleaner way to map multiple dicts

Example:
https://gist.github.com/AbsoluteMSTR/68390af8d2533ff48cf0

**Comment by ssato** [comment]
Thanks a lot again for your info! 

I'm also thinking about collections.ChainMap to implement it, however, its availability in
python 2.x should be a problem as you said. Also I already made MergeableDict's successor
as another library, m9dicts: https://github.com/ssato/python-m9dicts, to allow extending
merge algorithm as needed. So I choose to use m9dicts as of now instead of collections.ChainMap.

**Comment by ssato** [comment]
Maybe collections.ChainMap would be an alternative until compatibility issues are resolved in python 2.x. Right now make it closed.
