### ISSUE TITLE
The order of items are not kept in YAML backend

### ISSUE THREAD

**Issue by ssato** [ssato/python-anyconfig#38]
It's possible but not easy to keep items load from YAML files. see:
- http://pyyaml.org/ticket/29
- http://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts

**Comment by AbsoluteMSTR** [comment]
Possibly use [rtyaml](https://github.com/unitedstates/rtyaml) instead of pyyaml to preserve order and comments. rtyaml builds on top of pyyaml.

**Comment by ssato** [comment]
Thanks a lot for your info! I was not aware of [rtyaml](https://github.com/unitedstates/rtyaml).
It feels promising in various point of views and I will look into it.

**Comment by ssato** [comment]
The commit 76508b7 improved and fixed this and now we can load YAML files with the order of items kept.

**Comment by AnkurDedania** [comment]
update, I would reconsider now with [ruamel.yaml](https://yaml.readthedocs.io/en/latest/overview.html). Supports the latest YAML 1.2 standard unlike PyYAML.

**Comment by ssato** [comment]
@AnkurDedania Thanks a lot! I'll look into it also.

**Comment by ssato** [comment]
@AnkurDedania Just FYI. I changed the yaml backend to use [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml) instead of PyYAML if it's available: 551c0fd
