### ISSUE TITLE
Dumping a ini file adds newline after every key

### ISSUE THREAD

**Issue by ajays20078** [ssato/python-anyconfig#41]
Input:

[server]
host = localhost
port = 8080

After using anyconfig.dump()

[server]

host = localhost

port = 8080

**Comment by ssato** [comment]
Thanks for your report!

I guess that the commit 0f975f2ef9054f27876c2f36d8cdd4c20c72a57e may fix this.
Could you please try the head version of master branch?

**Comment by ajays20078** [comment]
That seems to fix the issue. Closing this Issue.
