### ISSUE TITLE
Why are comments removed from .properties file?

### ISSUE THREAD

**Issue by ajays20078** [ssato/python-anyconfig#48]
Hi,

The comments from .properties files are getting removed by the parser [here](https://github.com/ssato/python-anyconfig/blob/6450527e5691652ff2cafac94e9a39c6bcc087ab/anyconfig/backend/properties.py#L80) . Is there a reason for removing the comments? Can't they be kept as it is?

**Comment by ssato** [comment]
Hi @ajays20078, 

Thanks a lot for your feedback again.

The reason anyconfig's .properties parser removing comments is that it's simply
somewhat hard to keep comments and white spaces as these exactly are, I think.

Also,  the purpose of anyconfig is to provide common APIs to access to configuration files
in various formats originally. It's intended to be just interface to other parers like anydbm
and I feel it should be over-engineering if I started to implement highly functional parsers
for each configuration formats.

If it's needed, IMHO, it should be better to start another project to support these formats.

BTW, it seems that pyproperties (https://github.com/marekjm/pyproperties) can keep
comments in .properties files:

  https://github.com/marekjm/pyproperties/blob/master/modules/pyproperties.py#L145

**Comment by ajays20078** [comment]
Thanks for reverting,  whatever you mentioned does make sense.
