### ISSUE TITLE
Can't read a yml file inside a docker container

### ISSUE THREAD

**Issue by m3talstorm** [ssato/python-anyconfig#60]
Dockerfile:

```
FROM ubuntu:16.10

RUN apt-get update && apt-get install -y

# Install dependancies
RUN apt-get -qq -y install python-pip

RUN pip install --upgrade pip
RUN pip install anyconfig

# Typically you would copy some files over
# ADD . /app

WORKDIR /app
```

Build the image:

`sudo docker build -t anyconfig .`

Run the image:

`sudo docker run -it anyconfig /bin/bash`

You will get a prompt into the container:

```
root@6d7c39775bb3:/app# echo "test: 1" > test.yml
root@6d7c39775bb3:/app# cat test.yml
test: 1
root@6d7c39775bb3:/app# ls
test.yml
root@6d7c39775bb3:/app#
root@6d7c39775bb3:/app# python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02)
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, anyconfig
>>> os.getcwd()
'/app'
>>> anyconfig.load('test.yml')
>>> with open('test.yml') as fd:
...     print fd.read()
...
test: 1

>>>

```

Notice how anyconfig just returns None, like it can't find the file :(

**Comment by ssato** [comment]
I guess that 'RUN pip install anyconfig' should be 'RUN pip install anyconfig PyYAML'.
Please take a look at https://github.com/ssato/python-anyconfig#user-content-supported-configuration-formats which mentions requirements for each configuration formats also.

**Comment by ssato** [comment]
P.S. issue #55 is related also.

**Comment by m3talstorm** [comment]
Ye that was it :)

I would highly suggest throwing and exception or at least warning users that it can't parse the content of a file or there are no loaded parsers etc.

**Comment by ssato** [comment]
> I would highly suggest throwing an exception or at least warning users

Absolutely right but that causes API break so that I've not been changed that behavior.
I'm now reconsidering to bring that change and maybe I'll make so in the next release.

**Comment by ssato** [comment]
FYI. I changed the API to fail first as much as possible it cannot find the parser (that is, if the backend module was not found or something goes wrong) by the commits in the master tree: 8ed4123 , b85c8a2 and 408ecbb .

**Comment by m3talstorm** [comment]
@ssato Thanks for the change and the heads-up
