### ISSUE TITLE
An issue when parsing java properties with colon in value

### ISSUE THREAD

**Issue by wstranger** [ssato/python-anyconfig#61]
There is an issue when parsing java properties with colon in value.
Example:

```
In [11]: anyconfig.__version__
Out[11]: '0.7.0'

In [12]: anyconfig.loads("url=http://localhost", ac_parser="properties")
Out[12]: {'url=http': '//localhost'}
```
Expected result:
`{'url': 'http://localhost'}`

**Comment by ssato** [comment]
Thanks a lot for your report! I'll take some time and look into this this weekend.

**Comment by ssato** [comment]
I guess that 3551454 which I have just pushed may resolve this.

**Comment by ssato** [comment]
It now works as far as I tested with the latest 0.8.1 release. Could you please take a look at it?

```python
In [2]: anyconfig.__version__
Out[2]: '0.8.1'

In [3]: anyconfig.loads("url=http://localhost", ac_parser="properties")
Out[3]: {'url': 'http://localhost'}
```

**Comment by wstranger** [comment]
Thank you. Now it works correctly.

**Comment by ssato** [comment]
Thanks, I close this.
