### ISSUE TITLE
Error during unittest

### ISSUE THREAD

**Issue by edyan** [ssato/python-anyconfig#80]
Hi,

When I run a unit test I get the following error:

`lib/python3.5/site-packages/anyconfig/backend/base.py:453: ResourceWarning: unclosed file <_io.TextIOWrapper name='tests/static/config_empty.yml' mode='r' encoding='UTF-8'>`

Is there any method to close the opened files ?

Thanks

**Comment by ssato** [comment]
Thanks for the report!

I'll take a look at it.

**Comment by ssato** [comment]
I think it was fixed by the commit e049c82. Could you please check with it?

**Comment by edyan** [comment]
Hi,

It works well !

Thanks for the fix
