### ISSUE TITLE
No module named pkg_resources

### ISSUE THREAD

**Issue by shivanetha** [ssato/python-anyconfig#95]
i'm trying to use anyconfig library in AWS Lambda, i'm getting the following error

Unable to import module 'service': No module named pkg_resources

any idea how to fix this

**Comment by ssato** [comment]
Excuse me that I forgot to specify the dependency to setuptools in setup.cfg and that is resolved with the commit 740d90b.

Until the fixed version is released, please install setuptools explicitly also along with anyconfig.
Sorry for the inconvenience.

**Comment by ssato** [comment]
I've just released the latest 0.9.8 version contains the fixes for this issue and let it closed. Please let me know if you have any further related issues on this.

Thanks again for your report!
